version: '3'
services:
  PartyA-node:
    container_name: template-network-PartyA
    image: corda/corda-dev:latest
    command:
    - corda-dev-network-agent
    - node
    - template-network-PartyA
    - http://template-network-bootstrapper:8080/
    networks:
    - template-network
    depends_on:
    - bootstrapper
    ports:
    - 12111:10000
    - 12112:8888
    - 12113:9000
    - 12114:12114
    labels:
      type: corda
      x500: C=US, L=Los Angeles, O=PartyA, OU=LLC
    environment:
      CORDA_DEBUG_PORT: '12114'
    volumes:
    - source: /Users/vincentjuge/.corda/template-network/docker_compose/tmp/PartyA
      target: /opt/nodes/
      type: bind
  PartyB-node:
    container_name: template-network-PartyB
    image: corda/corda-dev:latest
    command:
    - corda-dev-network-agent
    - node
    - template-network-PartyB
    - http://template-network-bootstrapper:8080/
    networks:
    - template-network
    depends_on:
    - bootstrapper
    ports:
    - 12115:10000
    - 12116:8888
    - 12117:9000
    labels:
      type: corda
      x500: C=GB, L=London, O=PartyB, OU=INC
    environment: &id001 {
      }
    volumes:
    - source: /Users/vincentjuge/.corda/template-network/docker_compose/tmp/PartyB
      target: /opt/nodes/
      type: bind
  notary-node:
    container_name: template-network-notary
    image: corda/corda-dev:latest
    command:
    - corda-dev-network-agent
    - node
    - template-network-notary
    - http://template-network-bootstrapper:8080/
    networks:
    - template-network
    depends_on:
    - bootstrapper
    ports:
    - 12118:10000
    - 12119:8888
    - 12120:9000
    labels:
      type: corda
      x500: O=notary, L=London, C=GB
      notary: 'true'
    environment: *id001
    volumes:
    - source: /Users/vincentjuge/.corda/template-network/docker_compose/tmp/notary
      target: /opt/nodes/
      type: bind
  bootstrapper:
    container_name: template-network-bootstrapper
    image: corda/corda-dev:latest
    networks:
    - template-network
    command:
    - python3
    - -u
    - scaffold.py
    - --node
    - template-network-PartyA
    - |-
      {"legal_name": "C=US, L=Los Angeles, O=PartyA, OU=LLC", "rpcUsers": [{"user": "user1",
            "password": "test", "permissions": ["ALL"]}, {"user": "angelenos", "password": "password",
            "permissions": ["ALL"]}]}
    - --node
    - template-network-PartyB
    - |-
      {"legal_name": "C=GB, L=London, O=PartyB, OU=INC", "rpcUsers": [{"user": "user1",
            "password": "test", "permissions": ["ALL"]}, {"user": "londoner", "password": "password",
            "permissions": ["ALL"]}]}
    - --notary
    - template-network-notary
    - |-
      {"legal_name": "O=notary, L=London, C=GB", "rpcUsers": [{"user": "user1", "password": "test",
            "permissions": ["ALL"]}]}
    environment:
      NODE_BOOTSTRAPPER_TIMEOUT: '20'
    labels:
      type: bootstrapper
    volumes:
    - source: /Users/vincentjuge/.corda/template-network/docker_compose/tmp/bootstrapper
      target: /opt/nodes/
      type: bind
networks:
  template-network:
    name: template-network

